### ISSUE TITLE
An error related to Pydantic has occurred.

### ISSUE THREAD

**Issue by VAN613** [Azure/gpt-rag-orchestrator#110]
The code that was previously functioning correctly has stopped working. The error code is as follows, and it seems to be related to semantic-kernel:

ImportError: cannot import name 'Url' from 'pydantic.networks' (/home/site/wwwroot/.python_packages/lib/site-packages/pydantic/networks.py)

For the time being, I was able to avoid the error by explicitly specifying "pydantic == 2.9.2" in the "requirements.txt" file, but if there are any better solutions, I would appreciate your guidance.

https://github.com/microsoft/semantic-kernel/issues/9777

**Comment by jucastag** [comment]
I had the same issue and also temporarily fixed it with "pydantic == 2.9.2".

Any updates would be great.
thanks

**Comment by VAN613** [comment]
Thank you for the recent fix to requirements.txt in this repository and in gpt-rag-ingestion.

Separately, I encountered an issue where indexer creation in gpt-rag-ingestion suddenly started failing, and I was unable to determine the root cause. However, your fix seems to have resolved the issue and everything is working as expected now. I'll go ahead and close this issue.

Additional Note:

While I haven't fully identified all contributing factors, it seems that openai==1.55.3 is a requirement for proper functionality.
https://community.openai.com/t/client-openai-returns-error-client-init-got-an-unexpected-keyword-argument-proxies/1035249/5
