### ISSUE TITLE
Search Query Generation

### ISSUE THREAD

**Issue by cahuja1992** [Azure/gpt-rag-orchestrator#23]
Don't we need to generate search query generator like https://github.com/Azure-Samples/azure-search-openai-demo/blob/144698a382bd9ad1375ee23824fa2ba0cbf7c3d6/app/backend/approaches/chatreadretrieveread.py#L45

**Comment by placerda** [comment]
> Don't we need to generate search query generator like https://github.com/Azure-Samples/azure-search-openai-demo/blob/144698a382bd9ad1375ee23824fa2ba0cbf7c3d6/app/backend/approaches/chatreadretrieveread.py#L45

Hi @cahuja1992, good point, I just add this feature to the new Triage function prompt: 
"If you have chosen 'question_answering', generate the 'QUERY_STRING'..."

**Comment by placerda** [comment]
> Don't we need to generate search query generator like https://github.com/Azure-Samples/azure-search-openai-demo/blob/144698a382bd9ad1375ee23824fa2ba0cbf7c3d6/app/backend/approaches/chatreadretrieveread.py#L45

Hi @cahuja1992, good point, I just add this feature to the new Triage function: 'If you have chosen 'question_answering', generate the 'QUERY_STRING''
